# Generated by Django 2.0.6 on 2018-06-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0003_link_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='date',
        ),
    ]
